### ISSUE TITLE
Backend Details - HELP

### ISSUE THREAD

**Issue by JaleelNazir** [theofficialvkr/VKRdownloader#14]
Could you kindly share the details about the backend architecture you're using? Additionally, if you're utilizing any open-source repositories, I would appreciate it if you could provide that information as well.

Thank you!

**Comment by theofficialvkr** [comment]
Just yt-dlp

**Comment by hamzamayo786-glitch** [comment]
but ytdlp gives hls m3u8 links:
https://skyfire.vimeocdn.com/1729416855-0x2d0464cac5700151e35d02cbe8260d496d715be6/a6e5411b-0d73-47a4-8db9-65547e553596/v2/playlist/av/a6e5411b/avf/596e145d/media.m3u8?pathsig=8c953e4f~j7VedcB4VffLe8gH8HuGuqqYF5RkmMU0bYjNwZrLFPA&qsr=1&sf=ts&st=video

but your site gives mp4 downloadable links:
https://player.vimeo.com/progressive_redirect/playback/874986396/container/a6e5411b-0d73-47a4-8db9-65547e553596/f05db432-9490df1c?expires=1729502406&loc=external&session_id=0bdb197b8ad558e8de664bc680d0a6e1d1fdda0e1729415886&signature=7725ac7cdb096bd51d7d7560657db9d107a97d9f13386e99f935db1ddd33c381

how you are doing this can you help plz!
