### ISSUE TITLE
ytdlp

### ISSUE THREAD

**Issue by hamzamayo786-glitch** [theofficialvkr/VKRdownloader#15]
but ytdlp gives hls m3u8 links:
https://skyfire.vimeocdn.com/1729416855-0x2d0464cac5700151e35d02cbe8260d496d715be6/a6e5411b-0d73-47a4-8db9-65547e553596/v2/playlist/av/a6e5411b/avf/596e145d/media.m3u8?pathsig=8c953e4f~j7VedcB4VffLe8gH8HuGuqqYF5RkmMU0bYjNwZrLFPA&qsr=1&sf=ts&st=video

but your site gives mp4 downloadable links:
https://player.vimeo.com/progressive_redirect/playback/874986396/container/a6e5411b-0d73-47a4-8db9-65547e553596/f05db432-9490df1c?expires=1729502406&loc=external&session_id=0bdb197b8ad558e8de664bc680d0a6e1d1fdda0e1729415886&signature=7725ac7cdb096bd51d7d7560657db9d107a97d9f13386e99f935db1ddd33c381

how you are doing this can you help plz!

**Comment by theofficialvkr** [comment]
For Vimeo video?

**Comment by hamzamayo786-glitch** [comment]
for all sites your server gives mp4 links for multiples resolutions including vimeo but ytdlp gives m3u8 links for some sites specifically vimeo but if i pass vimeo cookies then it gives only one mp4 link and rest of all in m3u8.i just want to know how your ytdlp server returns mp4 links for all sites.

**Comment by theofficialvkr** [comment]
First -  Its not just depends on yt-dlp 

Second - use cookies.txt

**Comment by hamzamayo786-glitch** [comment]
can you share info of your ytdlp server?
