### ISSUE TITLE
stop autoplaying the video please

### ISSUE THREAD

**Issue by DereC4** [theofficialvkr/VKrDownloader#19]
nice site you've got, however i feel like it's more beneficial to have the video start as paused and allow people to choose to play it or not, rather than have it automatically play

![image](https://github.com/user-attachments/assets/3759fef9-f1ab-4a87-99a4-db0a501943b5)

This could also just be a toggle so the user could choose. It's just a nitpick but lemme know yalls thoughts

**Comment by theofficialvkr** [comment]
Okay sir fixed 👍
