### ISSUE TITLE
https://theofficialvkr.github.io/VKRdownloader/ is not working

### ISSUE THREAD

**Issue by manojrhr** [theofficialvkr/VKRdownloader#8]
Hi Vijay,

I have tried the demo on https://theofficialvkr.github.io/VKRdownloader/ link but its not downloading the video from a twitter link e.g. I am using this link to download a video:

https://twitter.com/NoloFCB/status/1552917869834412034

Can you please tell, how to download a twitter video using your script?

**Comment by theofficialvkr** [comment]
It's working 
![Screenshot_20220730-204019_1](https://user-images.githubusercontent.com/58748754/181923676-bdd58f58-cc86-4b85-855e-942ed7b9dea5.jpg)

**Comment by manojrhr** [comment]
It is showing this error message.
![image](https://user-images.githubusercontent.com/17489198/182193390-6ddf518a-e63b-4033-b006-6e476932702c.png)

and also it is giving null
![image](https://user-images.githubusercontent.com/17489198/182193684-5548cf8c-ce18-4b15-8391-1b7419f5e610.png)

Sometimes its showing this error message.
![image](https://user-images.githubusercontent.com/17489198/182194094-182546af-cdf1-40ec-b1ad-9170acc8aa57.png)

**Comment by theofficialvkr** [comment]
Due to too many requests... But still i almost fixed it..
